### ISSUE TITLE
cant load plugin  com.mercadolibre.plugins.csv.CsvFunctionPlugin not found

### ISSUE THREAD

**Issue by Manjukb** [alcampos/graylog-plugin-function-csv#1]
i download .jar and placed it in /plugin folder after restarting i got below error 

>  java.util.ServiceConfigurationError: org.graylog2.plugin.Plugin: Provider com.mercadolibre.plugins.csv.CsvFunctionPlugin not found

**Comment by alcampos** [comment]
Forgot to change reference, thanks!

**Comment by alcampos** [comment]
Should work in version 0.0.4

**Comment by Manjukb** [comment]
Thanks will check it
